/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Id = IDL.Nat;
export const GratitudeEntry = IDL.Record({
  'id' : Id,
  'text' : IDL.Text,
  'timestamp' : IDL.Int,
  'category' : IDL.Opt(IDL.Text),
});
export const Goal = IDL.Record({
  'id' : Id,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'completed' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addEntry' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [GratitudeEntry], []),
  'addGoal' : IDL.Func([IDL.Text], [Goal], []),
  'deleteEntry' : IDL.Func([Id], [], []),
  'deleteGoal' : IDL.Func([Id], [], []),
  'getEntries' : IDL.Func([], [IDL.Vec(GratitudeEntry)], ['query']),
  'getGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
  'getSuggestedGoals' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'updateGoal' : IDL.Func([Id, IDL.Bool], [Goal], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Id = IDL.Nat;
  const GratitudeEntry = IDL.Record({
    'id' : Id,
    'text' : IDL.Text,
    'timestamp' : IDL.Int,
    'category' : IDL.Opt(IDL.Text),
  });
  const Goal = IDL.Record({
    'id' : Id,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'completed' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addEntry' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [GratitudeEntry], []),
    'addGoal' : IDL.Func([IDL.Text], [Goal], []),
    'deleteEntry' : IDL.Func([Id], [], []),
    'deleteGoal' : IDL.Func([Id], [], []),
    'getEntries' : IDL.Func([], [IDL.Vec(GratitudeEntry)], ['query']),
    'getGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
    'getSuggestedGoals' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'updateGoal' : IDL.Func([Id, IDL.Bool], [Goal], []),
  });
};

export const init = ({ IDL }) => { return []; };