/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Id = IDL.Nat;
export const GratitudeEntry = IDL.Record({
  'id' : Id,
  'text' : IDL.Text,
  'timestamp' : IDL.Int,
  'category' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'addEntry' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [GratitudeEntry], []),
  'deleteEntry' : IDL.Func([Id], [], []),
  'getEntries' : IDL.Func([], [IDL.Vec(GratitudeEntry)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Id = IDL.Nat;
  const GratitudeEntry = IDL.Record({
    'id' : Id,
    'text' : IDL.Text,
    'timestamp' : IDL.Int,
    'category' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'addEntry' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [GratitudeEntry], []),
    'deleteEntry' : IDL.Func([Id], [], []),
    'getEntries' : IDL.Func([], [IDL.Vec(GratitudeEntry)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };